name: ncmb
version: 0.1.2
description: >-
  Dart and Flutter library for Nifcloud mobile backend(NCMB). Nifcloud mobile backend is a web service of mBaaS.
homepage: https://github.com/NCMBMania/ncmb-dart

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  crypto: ^2.1.3
  intl: ^0.16.1
  package_info: ^0.4.0+13
  plain_notification_token: ^0.0.1
  notification_reactor: ^0.0.3+1
  dio: ^3.0.8
  mime: ^0.9.6+3
  http_parser: ^3.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
