name: ncmb
version: 2.3.2
description: >-
  Dart and Flutter library for Nifcloud mobile backend(NCMB). Nifcloud mobile backend is a web service of mBaaS.
homepage: https://github.com/NCMBMania/ncmb-dart

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  crypto: ^3.0.1
  intl: ^0.17.0
  package_info: ^2.0.2
  dio: ^4.0.3
  mime: ^1.0.1
  http_parser: ^4.0.0
  uuid: ^3.0.5
  shared_preferences: ^2.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
