name: ncmb
version: 0.0.1
description: >-
  
homepage: https://github.com/NCMBMania/ncmb-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  crypto: ^2.1.4
dev_dependencies:
  test: ^1.3.4
