name: ncmb
version: 0.0.8
description: >-
  Dart and Flutter library for Nifcloud mobile backend(NCMB). Nifcloud mobile backend is a web service of mBaaS.
homepage: https://github.com/NCMBMania/ncmb-dart

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  crypto: ^2.1.4
  intl: ^0.16.1
dev_dependencies:
  test: ^1.3.4
