name: ncmb
version: 2.0.1
description: >-
  Dart and Flutter library for Nifcloud mobile backend(NCMB). Nifcloud mobile backend is a web service of mBaaS.
homepage: https://github.com/NCMBMania/ncmb-dart

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  crypto: ^2.1.3
  intl: ^0.16.1
  package_info: ^0.4.0+13
  dio: ^3.0.8
  mime: ^0.9.6+3
  http_parser: ^3.1.3
  uuid: ^2.0.4
  shared_preferences: ^0.5.6+2
dev_dependencies:
  flutter_test:
    sdk: flutter
