name: ncmb
version: 2.0.2
description: >-
  Dart and Flutter library for Nifcloud mobile backend(NCMB). Nifcloud mobile backend is a web service of mBaaS.
homepage: https://github.com/NCMBMania/ncmb-dart

environment:
  sdk: ">=2.5.0 <3.0.0"
dependencies:
  crypto: ^2.1.5
  intl: ^0.16.1
  package_info: ^0.4.0+13
  dio: ^3.0.10
  mime: ^0.9.7
  http_parser: ^3.1.4
  uuid: ^2.2.2
  shared_preferences: ^0.5.12+4
dev_dependencies:
  flutter_test:
    sdk: flutter
